## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key

from config import g_key
from config import weather_api_key
# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
file = "../Vacation_Search/WeatherPy_vacation.csv"
vacation_df = pd.read_csv(file)
vacation_df.head()

City_ID      City Country  Max Temp      Discription    Lat     Lng  \
0       13    Atuona      PF     78.75       light rain  -9.80 -139.03   
1       15  Luderitz     NaN     70.29        clear sky -26.65   15.16   
2       19    Albany      US     71.01  overcast clouds  42.60  -73.97   
3       20    Avarua      CK     75.20        clear sky -21.21 -159.78   
4       22     Avera      US     73.40        clear sky  33.19  -82.53   

            Hotel Name  
0          Villa Enata  
1  LÜDERITZ NEST HOTEL  
2                  NaN  
3         Paradise Inn  
4                  NaN

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
city_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]


# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=city_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.


vacation_start = vacation_df.loc[vacation_df["City"]=="Kowary"]
vacation_end = vacation_df.loc[vacation_df["City"]=="Kowary"]
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="Marienburg"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="Novara"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Paslek"]

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]]
starta = start.to_numpy()

end =  vacation_end[["Lat", "Lng"]]
enda = end.to_numpy()

stop1 = vacation_stop1[["Lat", "Lng"]]
stop1a = stop1.to_numpy()

stop2 = vacation_stop2[["Lat", "Lng"]]
stop2a = stop2.to_numpy()


stop3 = vacation_stop3[["Lat", "Lng"]]
stop3a = stop3.to_numpy()

print(starta)
print(enda)
print(stop1a)
print(stop2a)
print(stop3a)

[[50.79 15.84]]
[[50.79 15.84]]
[[54.04 19.03]]
[[45.59  8.58]]
[[54.06 19.66]]


In [8]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
Kowary = 50.79, 15.84
End_Kowary = 50.79, 15.84
Marienburg = 54.04, 19.03
Novara = 45.59, 8.58
Paslek = 54.06, 19.66

fig = gmaps.figure()
trip = gmaps.directions_layer(Kowary, End_Kowary, waypoints=[Marienburg, Novara, Paslek], travel_mode="DRIVING")
fig.add_layer(trip)
fig


Figure(layout=FigureLayout(height='420px'))

In [ ]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

In [ ]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 30.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig